config/routes.rb
Rails.application.routes.draw do
  resources :shopping_lists do
    resources :shopping_items
  end
  root "shopping_lists#index"
end

app/models/shopping_item.rb
class ShoppingItem < ActiveRecord::Base
  belongs_to :shopping_list
    #acts_as_list scope: :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
    has_many :shopping_items, -> { order(position: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shopping_items_controller.rb
class ShoppingItemsController < ApplicationController
    before_action :set_shopping_list
    
    
    def create
       @shopping_item = @shopping_list.shopping_items.create(shopping_item_params)
        redirect_to @shopping_list
    end
    
    
    def destroy
       @shopping_item = @shopping_list.shopping_items.find(params[:id])
       if @shopping_item.destroy
           flash[:success] = "Shopping List item was deleted."
       else
           flash[:error] = "Shopping List item could not be deleted"
       end
       redirect_to @shopping_list
    end
    

    
    private
    
    def set_shopping_list
        @shopping_list = ShoppingList.find(params[:shopping_list_id])
    end
    
    def shopping_item_params
        params[:shopping_item].permit(:content)
    end
    
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]

  # GET /shopping_lists
  # GET /shopping_lists.json
  def index
    @shopping_lists = ShoppingList.all
  end

  # GET /shopping_lists/1
  # GET /shopping_lists/1.json
  def show
  end

  # GET /shopping_lists/new
  def new
    @shopping_list = ShoppingList.new
  end

  # GET /shopping_lists/1/edit
  def edit
  end

  # POST /shopping_lists
  # POST /shopping_lists.json
  def create
    @shopping_list = ShoppingList.new(shopping_list_params)

    respond_to do |format|
      if @shopping_list.save
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list }
      else
        format.html { render :new }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_lists/1
  # PATCH/PUT /shopping_lists/1.json
  def update
    respond_to do |format|
      if @shopping_list.update(shopping_list_params)
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_list }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_lists/1
  # DELETE /shopping_lists/1.json
  def destroy
    @shopping_list.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list
      @shopping_list = ShoppingList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_params
      params.require(:shopping_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopping_items_helper.rb
module ShoppingItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/shopping_items/_form.html.erb
<%= form_for([@shopping_list, @shopping_list.shopping_items.build]) do |f| %>
    <%= f.text_field :content, placeholder: "New Shopping Item" %>
    <%= f.submit %>
<% end %>

app/views/shopping_items/_shopping_item.html.erb
<p><%= shopping_item.content %></p>
<%= link_to "Delete", shopping_list_shopping_item_path(@shopping_list, shopping_item.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/shopping_lists/_form.html.erb
<%= form_for(@shopping_list) do |f| %>
  <% if @shopping_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_list.errors.count, "error") %> prohibited this shopping_list from being saved:</h2>

      <ul>
      <% @shopping_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_lists/edit.html.erb
<h1>Editing Shopping List</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shopping Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_lists.each do |shopping_list| %>
      <tr>
        <td><%= shopping_list.title %></td>
        <td><%= shopping_list.description %></td>
        <td><%= link_to 'Show', shopping_list %></td>
        <td><%= link_to 'Edit', edit_shopping_list_path(shopping_list) %></td>
        <td><%= link_to 'Destroy', shopping_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping list', new_shopping_list_path %>

app/views/shopping_lists/new.html.erb
<h1>New Shopping List</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shopping_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shopping_list.description %>
</p>

<div id="shopping_items_wrapper">
  <%= render @shopping_list.shopping_items %> 
  <div id="form">
    <%= render "shopping_items/form" %> 
  </div>
</div>

<%= link_to 'Edit', edit_shopping_list_path(@shopping_list) %> |
<%= link_to 'Back', shopping_lists_path %>